// Mocks generated by Mockito 5.0.10 from annotations
// in event_app/test/mock/clients/repo/mock_repos.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;

import 'package:event_app/model/event/event.dart' as _i3;
import 'package:event_app/model/event/event_list_response.dart' as _i2;
import 'package:event_app/repo/event_rest_client.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeEventListResponse extends _i1.Fake implements _i2.EventListResponse {
}

class _FakeEvent extends _i1.Fake implements _i3.Event {}

/// A class which mocks [EventRestClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockEventRestClient extends _i1.Mock implements _i4.EventRestClient {
  MockEventRestClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.EventListResponse> getEventList(String? apiKey) =>
      (super.noSuchMethod(Invocation.method(#getEventList, [apiKey]),
              returnValue:
                  Future<_i2.EventListResponse>.value(_FakeEventListResponse()))
          as _i5.Future<_i2.EventListResponse>);
  @override
  _i5.Future<_i3.Event> getEventDetails(String? apiKey, String? id) =>
      (super.noSuchMethod(Invocation.method(#getEventDetails, [apiKey, id]),
              returnValue: Future<_i3.Event>.value(_FakeEvent()))
          as _i5.Future<_i3.Event>);
}
